/*
import org.junit.Test;
import static org.junit.Assert.*;
*/

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'aricci' at '12/27/16 10:52 PM' with Gradle 2.14.1
 *
 * @author aricci, @date 12/27/16 10:52 PM
 */
public class LibraryTest {
    /*
	@Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }*/
}
